//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterLinq.Tests.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterLinq.Tests.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;customers&gt;
        ///  &lt;customer&gt;
        ///    &lt;id&gt;ALFKI&lt;/id&gt;
        ///    &lt;name&gt;Alfreds Futterkiste&lt;/name&gt;
        ///    &lt;address&gt;Obere Str. 57&lt;/address&gt;
        ///    &lt;city&gt;Berlin&lt;/city&gt;
        ///    &lt;postalcode&gt;12209&lt;/postalcode&gt;
        ///    &lt;country&gt;Germany&lt;/country&gt;
        ///    &lt;phone&gt;030-0074321&lt;/phone&gt;
        ///    &lt;fax&gt;030-0076545&lt;/fax&gt;
        ///    &lt;orders&gt;
        ///      &lt;order&gt;
        ///        &lt;id&gt;10643&lt;/id&gt;
        ///        &lt;orderdate&gt;1997-08-25T00:00:00&lt;/orderdate&gt;
        ///        &lt;total&gt;814.50&lt;/total&gt;
        ///      &lt;/order&gt;
        ///      &lt;order&gt;
        ///        &lt;id&gt;10692&lt;/id&gt;
        ///        &lt;orderdate&gt;1997-10-03T00:00:00&lt;/o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
    }
}
