//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterLinq.Tests.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IMockQueryService")]
    public interface IMockQueryService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.interlinq.com/2011/03/server) of message RetrieveRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.interlinq.com/2011/03/server/IQueryRemoteHandler/Retrieve", ReplyAction="http://schemas.interlinq.com/2011/03/server/IQueryRemoteHandler/RetrieveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://schemas.interlinq.com/2011/03/server/IQueryRemoteHandler/RetrieveException" +
            "Fault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableInvocationExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableBinaryExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableLambdaExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableExpressionTyped))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableConditionalExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableConstantExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableListInitExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableNewExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableMemberExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableMemberInitExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableMethodCallExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableNewArrayExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableTypeBinaryExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableUnaryExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.Anonymous.AnonymousMetaType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.InterLinqType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.InterLinqMemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Types.Anonymous.AnonymousMetaProperty>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.Anonymous.AnonymousMetaProperty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.InterLinqPropertyInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.InterLinqFieldInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.InterLinqMethodBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Types.InterLinqType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.InterLinqConstructorInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.InterLinqMethodInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableTypes.SerializableMemberMemberBinding))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableTypes.SerializableMemberBinding))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableTypes.SerializableMemberListBinding))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Expressions.SerializableTypes.SerializableElementInit>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableTypes.SerializableElementInit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Expressions.SerializableExpression>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Expressions.SerializableTypes.SerializableMemberAssignment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Expressions.SerializableTypes.SerializableMemberBinding>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.Anonymous.AnonymousObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Types.Anonymous.AnonymousProperty>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.Anonymous.AnonymousProperty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Expressions.SerializableParameterExpression>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Types.InterLinqMemberInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.InterLinqQueryBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Types.Anonymous.InterLinqGroupingBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Types.Anonymous.AnonymousObject>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.InterLinqQuery<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.InterLinqQuery<InterLinq.Tests.Entities.Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.InterLinqQuery<InterLinq.Tests.Entities.Order>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.InterLinqQuery<InterLinq.Tests.Entities.Product>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.InterLinqQuery<InterLinq.Tests.Entities.Supplier>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Linq.Expressions.ExpressionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Linq.Expressions.MemberBindingType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Reflection.MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Reflection.MethodInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Reflection.MethodBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Tests.Entities.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Tests.Entities.Order>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Tests.Entities.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Tests.Entities.Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Tests.Entities.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Tests.Entities.Product>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InterLinq.Tests.Entities.Supplier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<InterLinq.Tests.Entities.Supplier>))]
        InterLinq.Tests.Server.RetrieveResponse Retrieve(InterLinq.Tests.Server.RetrieveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Retrieve", WrapperNamespace="http://schemas.interlinq.com/2011/03/server", IsWrapped=true)]
    public partial class RetrieveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.interlinq.com/2011/03/server", Order=0)]
        public InterLinq.Expressions.SerializableExpression expression;
        
        public RetrieveRequest() {
        }
        
        public RetrieveRequest(InterLinq.Expressions.SerializableExpression expression) {
            this.expression = expression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveResponse", WrapperNamespace="http://schemas.interlinq.com/2011/03/server", IsWrapped=true)]
    public partial class RetrieveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.interlinq.com/2011/03/server", Order=0)]
        public object RetrieveResult;
        
        public RetrieveResponse() {
        }
        
        public RetrieveResponse(object RetrieveResult) {
            this.RetrieveResult = RetrieveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMockQueryServiceChannel : InterLinq.Tests.Server.IMockQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MockQueryServiceClient : System.ServiceModel.ClientBase<InterLinq.Tests.Server.IMockQueryService>, InterLinq.Tests.Server.IMockQueryService {
        
        public MockQueryServiceClient() {
        }
        
        public MockQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MockQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MockQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MockQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterLinq.Tests.Server.RetrieveResponse InterLinq.Tests.Server.IMockQueryService.Retrieve(InterLinq.Tests.Server.RetrieveRequest request) {
            return base.Channel.Retrieve(request);
        }
        
        public object Retrieve(InterLinq.Expressions.SerializableExpression expression) {
            InterLinq.Tests.Server.RetrieveRequest inValue = new InterLinq.Tests.Server.RetrieveRequest();
            inValue.expression = expression;
            InterLinq.Tests.Server.RetrieveResponse retVal = ((InterLinq.Tests.Server.IMockQueryService)(this)).Retrieve(inValue);
            return retVal.RetrieveResult;
        }
    }
}
